
import './EditorTheme.css';

import type {EditorThemeClasses} from 'lexical';

// TASK : separate every class group into separate file
const theme: EditorThemeClasses = {
  autocomplete: 'anql_autocomplete',
  blockCursor: 'anql_blockCursor',
  characterLimit: 'anql_characterLimit',
  code: 'anql_code',
  codeHighlight: {
    atrule: 'anql_tokenAttr',
    attr: 'anql_tokenAttr',
    boolean: 'anql_tokenProperty',
    builtin: 'anql_tokenSelector',
    cdata: 'anql_tokenComment',
    char: 'anql_tokenSelector',
    class: 'anql_tokenFunction',
    'class-name': 'anql_tokenFunction',
    comment: 'anql_tokenComment',
    constant: 'anql_tokenProperty',
    deleted: 'anql_tokenDeleted',
    doctype: 'anql_tokenComment',
    entity: 'anql_tokenOperator',
    function: 'anql_tokenFunction',
    important: 'anql_tokenVariable',
    inserted: 'anql_tokenInserted',
    keyword: 'anql_tokenAttr',
    namespace: 'anql_tokenVariable',
    number: 'anql_tokenProperty',
    operator: 'anql_tokenOperator',
    prolog: 'anql_tokenComment',
    property: 'anql_tokenProperty',
    punctuation: 'anql_tokenPunctuation',
    regex: 'anql_tokenVariable',
    selector: 'anql_tokenSelector',
    string: 'anql_tokenSelector',
    symbol: 'anql_tokenProperty',
    tag: 'anql_tokenProperty',
    unchanged: 'anql_tokenUnchanged',
    url: 'anql_tokenOperator',
    variable: 'anql_tokenVariable',
  },
  embedBlock: {
    base: 'anql_embedBlock',
    focus: 'anql_embedBlockFocus',
  },
  hashtag: 'anql_hashtag',
  heading: {
    h1: 'anql_h1',
    h2: 'anql_h2',
    h3: 'anql_h3',
    h4: 'anql_h4',
    h5: 'anql_h5',
    h6: 'anql_h6',
  },
  hr: 'anql_hr',
  hrSelected: 'anql_hrSelected',
  image: 'editor-image',
  indent: 'anql_indent',
  layoutContainer: 'anql_layoutContainer',
  layoutItem: 'anql_layoutItem',
  link: 'anql_link',
  ltr: 'anql_ltr',
  mark: 'anql_mark',
  markOverlap: 'anql_markOverlap',
  paragraph: 'anql_paragraph',
  quote: 'anql_quote',
  rtl: 'anql_rtl',
  specialText: 'anql_specialText',
  tab: 'anql_tabNode',
  text: {
    bold: 'anql_textBold',
    capitalize: 'anql_textCapitalize',
    code: 'anql_textCode',
    highlight: 'anql_textHighlight',
    italic: 'anql_textItalic',
    lowercase: 'anql_textLowercase',
    strikethrough: 'anql_textStrikethrough',
    subscript: 'anql_textSubscript',
    superscript: 'anql_textSuperscript',
    underline: 'anql_textUnderline',
    underlineStrikethrough: 'anql_textUnderlineStrikethrough',
    uppercase: 'anql_textUppercase',
  },
};

export default theme;
